Repository syncfusion-content/ej2-asp-core-mvc-docs, pull requests merged in 2023-07, with the labels that each got.

#1806 Documentation(EJ2-834206) : To include UG for additional datasource for EJ2 Pivot Table
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/connecting-to-data-source/elasticsearch.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/connecting-to-data-source/microsoft-sql-server.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/connecting-to-data-source/mongodb.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/connecting-to-data-source/mysql.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/connecting-to-data-source/oracle.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/connecting-to-data-source/postgresql.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/connecting-to-data-source/snowflake.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/connecting-to-data-source/elasticsearch.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/connecting-to-data-source/microsoft-sql-server.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/connecting-to-data-source/mongodb.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/connecting-to-data-source/mysql.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/connecting-to-data-source/oracle.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/connecting-to-data-source/postgresql.md
  ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/connecting-to-data-source/snowflake.md
Labels: documentation

#1815 bug(836659): indicators Type documentation location is wrong
  ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/navigators-and-indicators.md
Labels: bug

#1826 documentation(834525): Full screen feature documentation added
  ej2-asp-core-mvc/datepicker/images/DatePickerFullScreen.gif
  ej2-asp-core-mvc/datepicker/style-appearance.md
  ej2-asp-core-mvc/daterangepicker/images/DateRangePickerDefaultFullScreen.gif
  ej2-asp-core-mvc/daterangepicker/images/DateRangePickerPresetsFullScreen.gif
  ej2-asp-core-mvc/daterangepicker/style-appearance.md
  ej2-asp-core-mvc/datetimepicker/images/DateTimePickerFullScreen.gif
  ej2-asp-core-mvc/datetimepicker/style-appearance.md
  ej2-asp-core-mvc/timepicker/images/TimePickerFullScreen.gif
  ej2-asp-core-mvc/timepicker/style-appearance.md
Labels: documentation

#1785 feature(834525): Full screen feature documentation added
  ej2-asp-core-mvc/datepicker/images/DatePickerFullScreen.gif
  ej2-asp-core-mvc/datepicker/style-appearance.md
  ej2-asp-core-mvc/daterangepicker/images/DateRangePickerDefaultFullScreen.gif
  ej2-asp-core-mvc/daterangepicker/images/DateRangePickerPresetsFullScreen.gif
  ej2-asp-core-mvc/daterangepicker/style-appearance.md
  ej2-asp-core-mvc/datetimepicker/images/DateTimePickerFullScreen.gif
  ej2-asp-core-mvc/datetimepicker/style-appearance.md
  ej2-asp-core-mvc/timepicker/images/TimePickerFullScreen.gif
  ej2-asp-core-mvc/timepicker/style-appearance.md
Labels: enhancement

#1821 Documentation(SC-43825): Added code snippets for converting .NET Core Web App from 2.2 code to 3.0 for Timezone topic in scheduler.
  ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/timezone.md
Labels: documentation

#1836 feature(834525): Full screen feature documentation added
  ej2-asp-core-mvc/datepicker/style-appearance.md
  ej2-asp-core-mvc/daterangepicker/style-appearance.md
  ej2-asp-core-mvc/datetimepicker/style-appearance.md
  ej2-asp-core-mvc/timepicker/style-appearance.md
Labels: documentation

#1837 feature(834525): Full screen feature documentation added
  ej2-asp-core-mvc/datepicker/style-appearance.md
  ej2-asp-core-mvc/daterangepicker/style-appearance.md
  ej2-asp-core-mvc/datetimepicker/style-appearance.md
  ej2-asp-core-mvc/timepicker/style-appearance.md
Labels: documentation

#1839 bug(ES-836265): failures in UG live publishing in carousel resolved
  ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/navigators-and-indicators.md
  ej2-asp-core-mvc/code-snippet/carousel/navigators/indicator-type-dynamic/indicator-dynamic.cs
Labels: bug

#1840 documentation(ES-837798-Core-and-mvc-docs): mapping the api links and fix navigate link issues
  ej2-asp-core-mvc/accordion/EJ2_ASP.MVC/getting-started.md
  ej2-asp-core-mvc/appbar/EJ2_ASP.MVC/getting-started.md
  ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/populating-items.md
  ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/populating-items.md
  ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/getting-started.md
  ej2-asp-core-mvc/tab/EJ2_ASP.MVC/getting-started.md
  ej2-asp-core-mvc/tab/how-to/create-wizard-using-tab.md
  ej2-asp-core-mvc/tab/how-to/prevent-content-swipe-selection.md
  ej2-asp-core-mvc/toolbar/EJ2_ASP.MVC/getting-started.md
Labels: documentation

#1842 feature(834525): Full screen feature documentation added
  ej2-asp-core-mvc/datepicker/style-appearance.md
  ej2-asp-core-mvc/daterangepicker/style-appearance.md
  ej2-asp-core-mvc/datetimepicker/style-appearance.md
  ej2-asp-core-mvc/timepicker/style-appearance.md
Labels: documentation

#1844 feature(834525): Full screen feature documentation added
  ej2-asp-core-mvc/datepicker/style-appearance.md
  ej2-asp-core-mvc/daterangepicker/style-appearance.md
  ej2-asp-core-mvc/datetimepicker/style-appearance.md
  ej2-asp-core-mvc/timepicker/style-appearance.md
Labels: documentation

#1847 documentation(ES-838283-ResolveConflict): Resolve conflict
  ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/navigators-and-indicators.md
  ej2-asp-core-mvc/code-snippet/carousel/navigators/indicator-type-dynamic/indicator-dynamic.cs
Labels: documentation

#1863 Documentation(ES-822852): Updated the UrlAdaptor UG topic with the example sample.
  ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/data-binding.md
Labels: documentation

#1867 documentation(ES-840066-Builderror): Resolve build error.
  ej2-asp-core-mvc/tab/how-to/create-wizard-using-tab.md
  ej2-asp-core-mvc/tab/how-to/prevent-content-swipe-selection.md
Labels: documentation
